### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 6FaNcY9** [redcode-labs/RedNixOS#10]
How to start the vm after nix build or will it deploy automatically.

Nix has a vm feature right??

**Comment by unrooted** [comment]
if you `nix build` the [alpha release](https://github.com/redcode-labs/RedNixOS/releases/tag/v0.1-alpha), it will output an .iso file, which can be used as a "regular" Linux .iso file - can easily be used with your hypervisor/ventoy/live system/your preferred way of using this
