### ISSUE TITLE
python3: command not found

### ISSUE THREAD

**Issue by lourkeur** [redcode-labs/RedNixOS#5]
# Steps to reproduce
```
[red@RedNixOS:~]$ python3
python3: command not found
```

# Expected behaviour
A python interpreter and REPL is available so that, for instance, `angr` can  be used. However this could be intended and I just don't know how to access Angr correctly.

# Root cause
~~the `python3` wrapper is actually the one from `pwntools`, so modules such as `unicorn` work, but other modules from `systemPackages` are not in path.~~ I am not sure putting modules in `systemPackages` works at all due to Nix peculiarities, it might be that one needs to do a `python3.buildEnv` or some such.

# Environment
257475bc55952b38a01ca7dd499c1379610fb3c9 installed inside Libvirt/QEMU

On the off chance that this is due to my idiosyncratic installation method, [I admit to it.](https://github.com/lourkeur/RedNixOS_guest)

**Comment by unrooted** [comment]
Hi, thanks for reporting the issue.
Interesting indeed. It's quite hard for just me to check whether **every** package works, so this can happen. 
Just checked on my VM, doesn't work either, and maybe I fucked my VM up during testing but also `python3` doesn't work for me. 
I have no idea why this doesn't work. 
Your project is nice, feel free to add some stuff from there here as well, would love to see that in here and every contribution is welcome.
Feel free to make a PR, or I'll push some changes after work today.

**Comment by lourkeur** [comment]
Thank you. I need to amend my report: in vanilla RedNixOS there is no `python3` indeed, the `python3` I was looking at came from my config. This leaves one question: what is the intended way to use `angr` (or `pyTenable` or any of the python modules) in this scenario? It seems like I cannot figure that out.

**Comment by unrooted** [comment]
Sorry, I forgot about it. Same with a 'normal' web browser (can be firefox). Add those, make a PR and add stuff you want, I'll just merge it.

I've just taken a look at maybe 50-60 tools if they work, so yeah. Sorry about it. Would be greatly appreciated if ya add those. 
I've also seen your PR to hackpkgs, nice one, gave you a thumbs up.

**Comment by unrooted** [comment]
Fixed lack of py3 in 95793b13828d79ff31da4fb25a4576d126903650
![image](https://user-images.githubusercontent.com/30440603/180874449-e8e4bc33-7385-4f9d-9d4a-32eada28dc18.png)

I don't know why it doesn't want to import `angr`, it has its place in `/nix/store`. 
![image](https://user-images.githubusercontent.com/30440603/180876497-2339caf4-0c2d-463a-a961-f1a5c63c4809.png)

Closing this for now. Feel free to open if sth else stops working. Looking forward to your other contributions. Feel free to add your stuff in here, that'd be greatly appreciated. Thanks.
